apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-def-svc-acc-psp
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:vmware-system-privileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
