apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnr-demo-psp
  namespace: cnr-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnr-restricted
subjects:
- kind: Group
  name: system:serviceaccounts:cnr-demo
