apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: dev-cluster
  namespace: test-namespace
spec:
  distribution:
    version: v1.20
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks:
        - 10.1.1.0/22
      services:
        cidrBlocks:
        - 10.1.4.0/22
      proxy:
        httpProxy: http://x.x.x.x:pppp  #Proxy URL for HTTP connections
        httpsProxy: http://x.x.x.x:pppp #Proxy URL for HTTPS connections
        noProxy:
        - x.x.x.x/y # Workload Network
        - x.x.x.x/y # Management Network
        - x.x.x.x/y # VIP Network
        - .local
        - .svc
        - .svc.cluster.local
  topology:
    controlPlane:
      count: 1
      class: best-effort-medium
      storageClass: tanzu-gold-storage-policy
    workers:
      count: 3
      class: best-effort-medium
      storageClass: tanzu-gold-storage-policy
