kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openemr-def-svc-acc-psp
  namespace: openemr
roleRef:
  kind: ClusterRole
  name: psp:vmware-system-privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: openemr
