apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencryptvolume
  namespace: openemr
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: tanzu-gold-storage-policy
  resources:
    requests:
      storage: 1Gi
