apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencryptvolume
  namespace: openemr
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-external
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sslvolume
  namespace: openemr
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-external
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: websitevolume
  namespace: openemr
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-external
  resources:
    requests:
      storage: 10Gi
