apiVersion: v1
kind: Service
metadata:
  name: openemr
  namespace: openemr
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  - name: "8090"
    port: 8090
    targetPort: 443
  selector:
    io.kompose.service: openemr
