apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-calculator
  labels:
    app: payment-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-calculator
  template:
    metadata:
      labels:
        app: payment-calculator
    spec:
      containers:
        - name: payment-calculator
          image: jeffgbutler/payment-calculator
          ports:
            - containerPort: 8080
          env:
            - name: spring.redis.host
              value: redis
            - name: spring.redis.port
              value: "6379"
            - name: spring.profiles.active
              value: redis
---
apiVersion: v1
kind: Service
metadata:
  name: payment-calculator
spec:
  selector:
    app: payment-calculator
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
