architecture: "standalone"
auth:
  rootPassword: "root"
first-run:
  database: ""
primary:
  persistence:
    enabled: false
secondary:
  persistence:
    enabled: false
serviceAccount:
  create: false
