apiVersion: v1
kind: Service
metadata:
  name: openemr
  namespace: openemr
spec:
  type: LoadBalancer
  ports:
  - name: "http" 
    port: 80
  - name: "https"
    port: 443
  selector:
    app: openemr
